image: erlang:21

before_script:
    - apt-get -q update
    - apt-get -y install cmake

test:
    variables:
        ERLANG_ROCKSDB_OPTS: "-DWITH_BUNDLE_LZ4=ON -DWITH_BUNDLE_SNAPPY=ON"
    script:
        - ./deps/rebar3 eunit

test-shared_libs:
    before_script:
        - apt-get update -qq && apt-get -y -qq install cmake liblz4-dev libsnappy-dev
    script:
        - ./deps/rebar3 eunit
