image: erlang:21

before_script:
    - apt-get -q update
    - apt-get -y install cmake

test:
    variables:
        ERLANG_ROCKSDB_OPTS: "-DWITH_BUNDLE_LZ4=ON -DWITH_BUNDLE_SNAPPY=ON"
    script:
        - ./deps/rebar3 eunit

test-shared_libs:
    before_script:
        - apt-get update -qq && apt-get -y -qq install cmake liblz4-dev libsnappy-dev
    variables:
        ERLANG_ROCKSDB_OPTS: "-DWITH_LZ4=ON -DWITH_SNAPPY=ON"
    script:
        - ./deps/rebar3 eunit

test-shared_rocksdb:
    before_script:
        - echo 'deb https://deb.debian.org/debian stretch-backports main' >/etc/apt/sources.list.d/backports.list
        - apt-get update -qq
        - apt-get -y -qq install cmake liblz4-dev libsnappy-dev
        - apt-get -y -t stretch-backports -qq install librocksdb-dev
    variables:
        ERLANG_ROCKSDB_OPTS: "-DWITH_SYSTEM_ROCKSDB=ON"
    script:
        - ./deps/rebar3 eunit
