before_script:
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - dpkg -i erlang-solutions_1.0_all.deb
  - apt-get update -y
  - apt-get install erlang
  - apt-get install g++-4.9
  - export CXX=g++-4.9

test:
  script:
    - ./rebar3 eunit

