version: '{build}'
image: Visual Studio 2017
environment:
  matrix:
  - erlang_vsn: 21.0
install:
- ps: >-
    choco install erlang --version $env:erlang_vsn

    choco install rebar3 --version 3.6.1
build_script:
- cmd: C:\ProgramData\chocolatey\lib\rebar3\tools\rebar3.cmd compile
test_script:
- cmd: C:\ProgramData\chocolatey\lib\rebar3\tools\rebar3.cmd eunit
notifications:
- provider: Email
  to:
  - bchesneau@pm.me
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
- path: '_build'
  name: build
  type: zip

