version: "{build}"
branches:
  only:
  - master
environment:
  matrix:
  - erlang_vsn: 21.0
install:
- ps: choco install rebar3
- ps: choco install erlang --version $env:erlang_vsn
build: false
test_script:
- ps: cmd.exe /c 'rebar3.cmd eunit'
notifications:
- provider: Email
  to:
  - bchesneau@pm.me
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false